name: Custom dispatch Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      opco:
        description: 'Select the opco value'
        required: true
        default: 'fintech'
      country:
        description: 'Select the country value'
        required: true
        default: 'india'
      env:
        description: 'Select the environment value'
        required: true
        default: 'stage'
        type: choice
        options:
          - dev
          - stage
          - prod
          - qa

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'ap-south-1'
      TF_VERSION: '1.8.0'

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: 'Terraform Init'
      run: terraform init -reconfigure -upgrade -input=false -no-color -backend-config "key=${{ github.event.inputs.opco }}-${{ github.event.inputs.country }}/${{ github.event.inputs.env }}/terraform.tfstate"

    - name: 'Terraform Plan Destroy'
      run: terraform plan -destroy -out=tfplan -no-color -input=false -var-file ./tfvars/${{ github.event.inputs.opco }}-${{ github.event.inputs.country }}/${{ github.event.inputs.env }}.tfvars

    - name: 'Terraform Destroy'
      if: github.ref == 'refs/heads/main'
      run: terraform apply -destroy -auto-approve tfplan
